SRCS = main.c ft_isalpha.c
OBJS = ${SRCS:.c=.o}
NAME = my_program
CFLAGS = -Wall -Werror -Wextra
CC = gcc
RM = rm -f

.c.o:
	${GCC} ${CFLAGS} -c $< -o ${<:.c=.o} -I.

${NAME}: ${OBJS}
	${GCC} -o ${NAME} ${OBJS}

all: ${NAME}

clean:
	${RM} ${OBJS}

fclean: clean
	${RM} ${NAME}

re: fclean all

.PHONY: all clean fclean re